In [48]:
import pandas as pd
sales =  pd.read_parquet(r"E:\Finemed_PharmaAI\data\04_silver\sales")

demand_df = pd.read_csv("demand_df.csv")

## Lag Features ##

In [8]:
# Lag period
lag_days = [1, 2, 3, 7, 14, 30]

for lag in lag_days:
    demand_df[f"Lag_{lag}"] = (
        demand_df
        .groupby("MDCODE")["Demand_Qty"]
        .shift(lag)
    )

In [10]:
sample = demand_df.loc[
    demand_df["MDCODE"] == "0158",
    [
        "MDCODE",
        "INVDT",
        "Demand_Qty",
        "Lag_1",
        "Lag_2",
        "Lag_3",
        "Lag_7",
        "Lag_14",
        "Lag_30"
    ]
]

sample.head(20)

Empty DataFrame
Columns: [MDCODE, INVDT, Demand_Qty, Lag_1, Lag_2, Lag_3, Lag_7, Lag_14, Lag_30]
Index: []

In [12]:
demand_df.isnull().sum()

MDCODE                     0
INVDT                      0
Demand_Qty                 0
Selling_Rate               0
Purchase_Rate              0
Maximum_Retail_Price       0
MDNAME                     0
PACKG                      0
DETAIL                  3477
day                       15
day_name                  15
day_of_week               15
week                      15
month                     15
month_name                15
quarter                   15
year                      15
is_weekend                15
financial_year            15
financial_month           15
Lag_1                    158
Lag_2                    315
Lag_3                    469
Lag_7                   1076
Lag_14                  2067
Lag_30                  4165
dtype: int64

In [14]:
# Rolling Mean Features


rolling_windows = [7, 14, 30]

for window in rolling_windows:
    demand_df[f"Rolling_Mean_{window}"] = (
        demand_df
        .groupby("MDCODE")["Demand_Qty"]
        .transform(
            lambda x: x.shift(1).rolling(window=window, min_periods=1).mean()
        )
    )

In [16]:
sample = demand_df.loc[
    demand_df["MDCODE"] == "0001",
    [
        "INVDT",
        "Demand_Qty",
        "Lag_1",
        "Lag_2",
        "Lag_3",
        "Lag_7",
        "Lag_14",
        "Lag_30"
    ]
]

sample.head(40)

Empty DataFrame
Columns: [INVDT, Demand_Qty, Lag_1, Lag_2, Lag_3, Lag_7, Lag_14, Lag_30]
Index: []

## Rolling Mean ##

In [19]:
# -------------------------------
# Rolling Mean Features
# -------------------------------

rolling_windows = [7, 14, 30]

for window in rolling_windows:
    demand_df[f"Rolling_Mean_{window}"] = (
        demand_df
        .groupby("MDCODE")["Demand_Qty"]
        .transform(
            lambda x: x.shift(1).rolling(window=window, min_periods=1).mean()
        )
    )

In [21]:
# -------------------------------
# Rolling Standard Deviation
# -------------------------------

for window in rolling_windows:
    demand_df[f"Rolling_STD_{window}"] = (
        demand_df
        .groupby("MDCODE")["Demand_Qty"]
        .transform(
            lambda x: x.shift(1).rolling(window=window, min_periods=1).std()
        )
    )

In [23]:
# -------------------------------
# Rolling Maximum
# -------------------------------

for window in [7, 30]:
    demand_df[f"Rolling_Max_{window}"] = (
        demand_df
        .groupby("MDCODE")["Demand_Qty"]
        .transform(
            lambda x: x.shift(1).rolling(window=window, min_periods=1).max()
        )
    )

In [25]:
# -------------------------------
# Rolling Minimum
# -------------------------------

for window in [7, 30]:
    demand_df[f"Rolling_Min_{window}"] = (
        demand_df
        .groupby("MDCODE")["Demand_Qty"]
        .transform(
            lambda x: x.shift(1).rolling(window=window, min_periods=1).min()
        )
    )

In [27]:
print(demand_df.shape)

print(demand_df.isnull().sum())

(84101, 36)
MDCODE                     0
INVDT                      0
Demand_Qty                 0
Selling_Rate               0
Purchase_Rate              0
Maximum_Retail_Price       0
MDNAME                     0
PACKG                      0
DETAIL                  3477
day                       15
day_name                  15
day_of_week               15
week                      15
month                     15
month_name                15
quarter                   15
year                      15
is_weekend                15
financial_year            15
financial_month           15
Lag_1                    158
Lag_2                    315
Lag_3                    469
Lag_7                   1076
Lag_14                  2067
Lag_30                  4165
Rolling_Mean_7           158
Rolling_Mean_14          158
Rolling_Mean_30          158
Rolling_STD_7            315
Rolling_STD_14           315
Rolling_STD_30           315
Rolling_Max_7            158
Rolling_Max_30           158
Rolling_Min_7            158
Rolling_Min_30           158
dtype: int64

In [29]:
sample = demand_df.loc[
    demand_df["MDCODE"] == "0001",
    [
        "INVDT",
        "Demand_Qty",
        "Lag_1",
        "Rolling_Mean_7",
        "Rolling_STD_7",
        "Rolling_Max_7",
        "Rolling_Min_7"
    ]
]

sample.head(20)

Empty DataFrame
Columns: [INVDT, Demand_Qty, Lag_1, Rolling_Mean_7, Rolling_STD_7, Rolling_Max_7, Rolling_Min_7]
Index: []

## Trend Features ##

In [32]:
# Day-to-day demand difference
demand_df["Demand_Diff_1"] = (
    demand_df
    .groupby("MDCODE")["Demand_Qty"]
    .transform(lambda x: x.diff())
)

In [34]:
# Percentage growth from previous day
demand_df["Demand_Growth_Rate"] = (
    demand_df
    .groupby("MDCODE")["Demand_Qty"]
    .transform(lambda x: x.pct_change())
)

In [36]:
# Difference compared to last week's demand
demand_df["Weekly_Trend"] = (
    demand_df["Demand_Qty"] - demand_df["Lag_7"]
)

In [38]:
print(demand_df.shape)

print(
    demand_df[
        [
            "Demand_Diff_1",
            "Demand_Growth_Rate",
            "Weekly_Trend"
        ]
    ].isnull().sum()
)

(84101, 39)
Demand_Diff_1          158
Demand_Growth_Rate     158
Weekly_Trend          1076
dtype: int64

In [40]:
sample = demand_df.loc[
    demand_df["MDCODE"] == "0001",
    [
        "INVDT",
        "Demand_Qty",
        "Lag_1",
        "Lag_7",
        "Demand_Diff_1",
        "Demand_Growth_Rate",
        "Weekly_Trend"
    ]
]

sample.head(20)

Empty DataFrame
Columns: [INVDT, Demand_Qty, Lag_1, Lag_7, Demand_Diff_1, Demand_Growth_Rate, Weekly_Trend]
Index: []

In [42]:
demand_df.shape

(84101, 39)

In [50]:
calendar_flags = sales[
    [
        "MDCODE",
        "INVDT",
        "is_month_start",
        "is_month_end",
        "is_quarter_end",
        "is_year_end"
    ]
]

print(calendar_flags.duplicated(subset=["MDCODE", "INVDT"]).sum())

55607

In [52]:
calendar_features = (
    sales[
        [
            "INVDT",
            "is_month_start",
            "is_month_end",
            "is_quarter_end",
            "is_year_end"
        ]
    ]
    .drop_duplicates(subset=["INVDT"])
)

In [54]:
demand_df = demand_df.merge(
    calendar_features,
    on="INVDT",
    how="left"
)

In [56]:
print(demand_df.shape)

(84101, 24)

In [60]:
demand_df

,MDCODE,INVDT,Demand_Qty,Selling_Rate,Purchase_Rate,Maximum_Retail_Price,MDNAME,PACKG,DETAIL,day,...,month_name,quarter,year,is_weekend,financial_year,financial_month,is_month_start,is_month_end,is_quarter_end,is_year_end
0,1,2017-12-21,10,15.000000,10.0,30.000000,OTACARE EAR DROPS,5ML,VIAL,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2018-01-02,30,42.530000,7.5,63.000000,OTACARE EAR DROPS,5ML,VIAL,2.0,...,January,1.0,2018.0,False,FY 2017-18,10.0,NaN,NaN,NaN,NaN
2,1,2018-01-03,130,40.350000,7.5,55.000000,OTACARE EAR DROPS,5ML,VIAL,3.0,...,January,1.0,2018.0,False,FY 2017-18,10.0,NaN,NaN,NaN,NaN
3,1,2018-01-04,25,37.570000,7.5,55.000000,OTACARE EAR DROPS,5ML,VIAL,4.0,...,January,1.0,2018.0,False,FY 2017-18,10.0,NaN,NaN,NaN,NaN
4,1,2018-01-05,380,35.632857,7.9,60.714286,OTACARE EAR DROPS,5ML,VIAL,5.0,...,January,1.0,2018.0,False,FY 2017-18,10.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84096,168,2023-04-24,30,55.000000,25.0,230.000000,PROZON-S INJECTION,1.5gm,1,24.0,...,April,2.0,2023.0,False,FY 2023-24,1.0,NaN,NaN,NaN,NaN
84097,168,2023-05-29,50,52.000000,25.0,230.000000,PROZON-S INJECTION,1.5gm,1,29.0,...,May,2.0,2023.0,False,FY 2023-24,2.0,NaN,NaN,NaN,NaN
84098,168,2026-03-13,20,70.000000,25.0,230.000000,PROZON-S INJECTION,1.5gm,1,13.0,...,March,1.0,2026.0,False,FY 2025-26,12.0,NaN,NaN,NaN,NaN
84099,168,2026-04-25,30,55.000000,25.0,230.000000,PROZON-S INJECTION,1.5gm,1,25.0,...,April,2.0,2026.0,True,FY 2026-27,1.0,NaN,NaN,NaN,NaN
84100,168,2026-05-26,50,52.000000,25.0,230.000000,PROZON-S INJECTION,1.5gm,1,26.0,...,May,2.0,2026.0,False,FY 2026-27,2.0,NaN,NaN,NaN,NaN

## Price Features ##

In [63]:
demand_df["Profit_Margin"] = (
    demand_df["Selling_Rate"] -
    demand_df["Purchase_Rate"]
)

In [65]:
demand_df["Profit_Percentage"] = (
    (
        demand_df["Selling_Rate"] -
        demand_df["Purchase_Rate"]
    )
    /
    demand_df["Purchase_Rate"]
) * 100

In [67]:
demand_df["Profit_Percentage"] = (
    (
        demand_df["Selling_Rate"] -
        demand_df["Purchase_Rate"]
    )
    /
    demand_df["Purchase_Rate"]
) * 100

In [69]:
demand_df["Discount_Percentage"] = (
    (
        demand_df["Maximum_Retail_Price"] -
        demand_df["Selling_Rate"]
    )
    /
    demand_df["Maximum_Retail_Price"]
) * 100

In [71]:
demand_df["Price_Change"] = (
    demand_df
    .groupby("MDCODE")["Selling_Rate"]
    .transform(lambda x: x.diff())
)

In [73]:
demand_df["Price_Growth"] = (
    demand_df
    .groupby("MDCODE")["Selling_Rate"]
    .transform(lambda x: x.pct_change())
)

In [75]:
demand_df["Price_Change"] = (
    demand_df
    .groupby("MDCODE")["Selling_Rate"]
    .transform(lambda x: x.diff())
)

## Product Features ##

In [80]:
### Medicine Frquency 
medicine_frequency = (
    demand_df
    .groupby("MDCODE")
    .size()
)

demand_df["Medicine_Frequency"] = (
    demand_df["MDCODE"]
    .map(medicine_frequency)
)

In [82]:
### Average Historical Demand

medicine_avg = (
    demand_df
    .groupby("MDCODE")["Demand_Qty"]
    .mean()
)

demand_df["Medicine_Avg_Demand"] = (
    demand_df["MDCODE"]
    .map(medicine_avg)
)

In [84]:
### Demand Volatility 

medicine_std = (
    demand_df
    .groupby("MDCODE")["Demand_Qty"]
    .std()
)

demand_df["Medicine_Demand_STD"] = (
    demand_df["MDCODE"]
    .map(medicine_std)
)

In [86]:
### Maximum Historical Demand 

medicine_max = (
    demand_df
    .groupby("MDCODE")["Demand_Qty"]
    .max()
)

demand_df["Medicine_Max_Demand"] = (
    demand_df["MDCODE"]
    .map(medicine_max)
)

In [88]:
### Number of Selling Days 

selling_days = (
    demand_df
    .groupby("MDCODE")["INVDT"]
    .nunique()
)

demand_df["Medicine_Selling_Days"] = (
    demand_df["MDCODE"]
    .map(selling_days)
)

In [90]:
display(demand_df.head().style)